### ISSUE TITLE
io:format/2 calls stored in the release DEBUG log files

### ISSUE THREAD

**Issue by yhafri** [zhongwencool/observer_cli#44]
When connecting `observer_cli` escript to one of our VMs (Erlang 21.0), we noticed that all `io:format/2` calls used by `observer_cli` where also send to our `debug.log` (we use the new `Logger` module) .

Then, the VM's CPU usage went super high.

Did anyone notice such a behavior?

**Comment by zhongwencool** [comment]
Your means CPU usage super high from `observer_cli` or system cmd `top`?
It  stays at a high level or periodic?

Because `io:format/2` only running every 1500ms. 
Then 3 ways to investigate this issue.
1. Don't use escript, only remote_console to your application and run `observer_cli:start().`
 To exclude `rpc` problem. （Possibility is very low).
2. Finish the previous step， then change to `reduction view` by enter **rr**, It's will show the top busy processes by [recon:proc_window/3](http://ferd.github.io/recon/recon.html#proc_window-3).
3. change to `reduction view` by enter **r**, It's will show the top busy processes by [recon:proc_count/2](http://ferd.github.io/recon/recon.html#proc_count-2).

**Comment by zhongwencool** [comment]
The refresh time is configurable now, but in inconvenient way. :(

It's can change two way:
1. `observer_cli:start(#view_opts{#home{interval=10000}}).`, but it's inconvenient. must include "observer_cli.hrl". and can't do this when using escript.

2. just as normal usage.
```
observer_cli:start().
```
then enter a  positive number (such as 10000), then press  *enter*
then the refresh time is `10000ms`.

------

I will do add `observer_cli:start(10000)` today. 
so as escript.  :)

**Comment by yhafri** [comment]
Awesome. Are you also planning to add it the `observer_cli` escript as a 3rd argument?
That would be great

**Comment by zhongwencool** [comment]
As your wish,  `1.3.4` is ready now.

**Comment by yhafri** [comment]
Thx and keep up the good work
